-- Seed data for testing speaker profiles
-- This file provides sample speaker profiles and embeddings for development and testing

BEGIN TRANSACTION;

-- Insert test speaker profiles
INSERT OR REPLACE INTO speaker_profiles (
    id, name, description, color, created_at, updated_at,
    identification_count, confidence_threshold, is_active,
    pitch_range_min, pitch_range_max, pitch_mean, speaking_rate,
    quality_features, gender, age_range_min, age_range_max, language_markers
) VALUES 
    (
        'test-speaker-001', 'John Smith', 'Test speaker profile for male voice', 
        '#3B82F6', datetime('now'), datetime('now'),
        5, 0.8, 1,
        80.0, 180.0, 120.0, 150.0,
        '{"clarity": 0.85, "stability": 0.92, "brightness": 0.65}',
        'male', 30, 45, '["en-US", "professional"]'
    ),
    (
        'test-speaker-002', 'Sarah Johnson', 'Test speaker profile for female voice',
        '#EF4444', datetime('now'), datetime('now'),
        8, 0.75, 1,
        150.0, 350.0, 220.0, 180.0,
        '{"clarity": 0.91, "stability": 0.87, "brightness": 0.78}',
        'female', 25, 35, '["en-US", "casual"]'
    ),
    (
        'test-speaker-003', 'Alex Chen', 'Test speaker profile for mixed accent',
        '#10B981', datetime('now'), datetime('now'),
        3, 0.7, 1,
        100.0, 250.0, 160.0, 140.0,
        '{"clarity": 0.79, "stability": 0.83, "brightness": 0.71}',
        null, null, null, '["en-US", "zh-CN", "multicultural"]'
    ),
    (
        'test-speaker-004', 'Maria Garcia', 'Test speaker profile with Spanish accent',
        '#F59E0B', datetime('now'), datetime('now'),
        2, 0.65, 1,
        140.0, 280.0, 190.0, 160.0,
        '{"clarity": 0.82, "stability": 0.89, "brightness": 0.73}',
        'female', 28, 40, '["es-ES", "en-US", "bilingual"]'
    ),
    (
        'test-speaker-005', 'Dr. Williams', 'Inactive test speaker profile',
        '#8B5CF6', datetime('now', '-30 days'), datetime('now', '-1 day'),
        15, 0.9, 0,
        90.0, 200.0, 135.0, 120.0,
        '{"clarity": 0.93, "stability": 0.95, "brightness": 0.68}',
        'male', 45, 60, '["en-GB", "academic"]'
    );

-- Insert sample voice embeddings (mock embeddings for testing)
-- In real usage, these would be generated by a speaker embedding model
INSERT OR REPLACE INTO voice_embeddings (
    id, speaker_id, vector, dimensions, model_name,
    quality_score, duration_seconds, created_at
) VALUES
    (
        'embed-001-001', 'test-speaker-001',
        -- Mock 8-dimensional embedding for testing (real embeddings would be 256-512 dims)
        X'3f8000003f0000003e8000003f4000003ec000003f2000003e4000003f600000',
        8, 'test_model_v1',
        0.92, 5.5, datetime('now', '-1 hour')
    ),
    (
        'embed-001-002', 'test-speaker-001',
        X'3f8000003f0000003e8000003f4000003ec000003f2000003e4000003f500000',
        8, 'test_model_v1',
        0.89, 3.2, datetime('now', '-2 hours')
    ),
    (
        'embed-002-001', 'test-speaker-002',
        X'3f4000003f8000003f0000003e8000003f6000003e4000003f2000003ec00000',
        8, 'test_model_v1',
        0.94, 4.8, datetime('now', '-30 minutes')
    ),
    (
        'embed-002-002', 'test-speaker-002',
        X'3f4000003f8000003f0000003e8000003f6000003e4000003f2000003eb00000',
        8, 'test_model_v1',
        0.87, 6.1, datetime('now', '-1 day')
    ),
    (
        'embed-003-001', 'test-speaker-003',
        X'3f0000003f4000003f8000003e8000003e4000003f6000003ec000003f200000',
        8, 'test_model_v1',
        0.85, 4.2, datetime('now', '-3 hours')
    ),
    (
        'embed-004-001', 'test-speaker-004',
        X'3e8000003f0000003f4000003f8000003f2000003ec000003f6000003e400000',
        8, 'test_model_v1',
        0.88, 5.9, datetime('now', '-45 minutes')
    ),
    (
        'embed-005-001', 'test-speaker-005',
        X'3f6000003e8000003f0000003f4000003f8000003f2000003ec000003e400000',
        8, 'test_model_v1',
        0.96, 7.3, datetime('now', '-2 days')
    );

-- Insert sample meeting speakers data
INSERT OR REPLACE INTO meeting_speakers (
    id, meeting_id, speaker_id, display_name,
    speaking_time_seconds, segment_count, average_confidence,
    first_spoken_at, last_spoken_at, is_verified, notes
) VALUES
    (
        'ms-001', 'meeting-demo-001', 'test-speaker-001', 'John Smith',
        180.5, 12, 0.87,
        datetime('now', '-2 hours'), datetime('now', '-1 hour'),
        1, 'Primary presenter'
    ),
    (
        'ms-002', 'meeting-demo-001', 'test-speaker-002', 'Sarah Johnson',
        95.2, 8, 0.91,
        datetime('now', '-2 hours'), datetime('now', '-1 hour'),
        1, 'Q&A participant'
    ),
    (
        'ms-003', 'meeting-demo-002', 'test-speaker-003', 'Alex Chen',
        220.8, 15, 0.83,
        datetime('now', '-1 day'), datetime('now', '-1 day', '+45 minutes'),
        0, null
    ),
    (
        'ms-004', 'meeting-demo-002', 'test-speaker-004', 'Maria Garcia',
        145.3, 10, 0.89,
        datetime('now', '-1 day'), datetime('now', '-1 day', '+40 minutes'),
        1, 'Technical expert'
    ),
    (
        'ms-005', 'meeting-demo-003', 'test-speaker-005', 'Dr. Williams',
        300.7, 20, 0.94,
        datetime('now', '-1 week'), datetime('now', '-1 week', '+1 hour'),
        1, 'Keynote speaker'
    );

COMMIT;

-- Verify seed data was inserted correctly
SELECT 'Speaker Profiles Count: ' || COUNT(*) FROM speaker_profiles;
SELECT 'Voice Embeddings Count: ' || COUNT(*) FROM voice_embeddings;
SELECT 'Meeting Speakers Count: ' || COUNT(*) FROM meeting_speakers;